[WIP] Broadcast Slashing on equivocation
OffchainLabs/prysm pull request #14693
Opened 2024-12-06 17:34 UTC by shyam-patel-kira

fixes #13088 

The PR implements immediate broadcasting of slashing messages when detecting equivocating blocks, helping the network react more quickly to malicious behavior without relying on the full slasher service processing.

2024-12-07 14:38 UTC, 0xalpharush commented on beacon-chain/blockchain/process_block.go
> +		return errors.Wrap(slashingErr, "could not detect equivocating block")
this should probably log instead of returning and preventing FCU? `could not check for block equivocation` seems more accurate

2024-12-07 14:47 UTC, 0xalpharush commented
I think this should probably be done in the gossip validation of beacon blocks for two reasons:
1) I may not understand the spec properly but I believe signing equivocating blocks even if they're invalid should bet met with a slashing proposal
2) There is probably no need for the slashing service to be sent a block which was already deemed equivocating and resulted in a slashing proposal being broadcast
https://github.com/prysmaticlabs/prysm/blob/30a136f1fbd3f62b02369be9878decbfdeb3b648/beacon-chain/sync/validate_beacon_blocks.go#L84-L95

Fwiw I am just an interested bystander using this as a learning opportunity. Feel free to ignore or let me know if this is unhelpful

2025-01-24 11:06 UTC, potuz requested changes

2025-01-24 11:06 UTC, potuz commented on beacon-chain/blockchain/process_block.go
> +	slashing, slashingErr := s.detectEquivocatingBlock(cfg.ctx, cfg.roblock)
This is the wrong spot to place this detection. An equivocation will never make it to this point since we check for `s.hasSeenBlockIndexSlot` during `validateBeaconBlockPubSub`.

2025-01-24 11:06 UTC, potuz commented on beacon-chain/blockchain/process_block.go
> +	if slashing != nil {
Better if the broadcasting logic is also handled by the helper so that it's encapsulated, the helper should call a broadcasting routine instead of returnning the slashing.

2025-01-24 11:06 UTC, potuz commented on beacon-chain/blockchain/service.go
> +		header1Root, err := header1.Header.HashTreeRoot()
No need to hash again here, you already have the root when you call this helper.

2025-01-24 11:06 UTC, potuz commented on beacon-chain/blockchain/service.go
> +		header2Root, err := header2.Header.HashTreeRoot()
Same here, the root is kept by the head package.

2025-01-24 11:11 UTC, potuz reviewed
When moving this check to the right spot instead after the call to `ReceiveBlock` we don't have the root yet (since we only hash after we know we haven't seen the block), we should check if the signatures are different instead, as a different root will result in a different signature.

2025-01-26 00:51 UTC, shyam-patel-kira commented on beacon-chain/blockchain/process_block.go
> +	if slashing != nil {
Addressed this in the next commit

2025-01-26 00:51 UTC, shyam-patel-kira commented on beacon-chain/blockchain/service.go
> +		header1Root, err := header1.Header.HashTreeRoot()
fixed this in the next commit

2025-01-26 01:17 UTC, shyam-patel-kira commented
Hey @potuz, Thanks for the review, addressed the changes that were requested

2025-02-03 21:52 UTC, potuz commented on beacon-chain/sync/validate_beacon_blocks.go
> +	existingSignedBlock, ok := existingBlock.(interfaces.ReadOnlySignedBeaconBlock)
`s.seenBlockCache` in the Sync package never returns a block , we set it for example in `setSeenBlockIndexSlot`

2025-02-03 23:41 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +	existingSignedBlock, ok := existingBlock.(interfaces.ReadOnlySignedBeaconBlock)
okay, current approach wouldn't work then. As suggested by you, made changes to use headBlock instead of blockCache for equivocation Detection.

2025-02-12 08:03 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +	if !s.hasSeenBlockIndexSlot(slot, proposerIndex) {
fixed this

2025-02-12 08:04 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +	if err := blocks.VerifyProposerSlashing(headState, slashing); err != nil {
Good catch! thanks

2025-02-12 08:04 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +	headState, err := s.cfg.chain.HeadStateReadOnly(ctx)
fixed it

2025-03-10 14:02 UTC, potuz commented on beacon-chain/sync/validate_beacon_blocks.go
> +	// Verify the slashing against current state
I may have been wrong in my previous review and if that is the case I apologize, but the function `VerifyProposerSlashing` already performs all the checks in `verifySlashableBlock` so I suggest the following changes
- Remove the function`verifySlashableBlock` 
- just call `VerifyProposerSlashing` after making sure that the signatures are different. 

However, there is a little care that needs to be taken. If `VerifyProposerSlashing` returns an error because the signature failed to verify, we need to return `PubsubReject` from the main block validation pipeline. 

The PR and it's logic looks good to me and I think it's safe to merge after this change.

2025-03-10 21:54 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +	// Verify the slashing against current state
Thanks for the feedback, Just pushed the changes

2025-03-11 13:29 UTC, potuz submitted a review, later dismissed
LGTM

2025-03-11 13:29 UTC, potuz commented on beacon-chain/sync/validate_beacon_blocks.go
> +		}
nit: is this he cleanest way to check this?

2025-03-11 18:33 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +		}
fixed this

2025-03-11 18:38 UTC, shyam-patel-kira commented
not sure why but it dismissed the review after I committed

2025-03-13 12:32 UTC, potuz commented on beacon-chain/sync/validate_beacon_blocks.go
> +			if errors.Is(err, ErrSlashingSignatureFailure) {
Where is this error being set?

2025-03-13 19:05 UTC, shyam-patel-kira commented on beacon-chain/sync/validate_beacon_blocks.go
> +			if errors.Is(err, ErrSlashingSignatureFailure) {
updated this to original logic

2025-03-17 15:42 UTC, potuz submitted a review, later dismissed

2025-03-21 17:53 UTC, rkapka commented on beacon-chain/sync/validate_beacon_blocks.go
> +		if strings.Contains(err.Error(), "could not verify beacon block header") {
It is very risky to compare errors like this because if someone modifies the original error message, this may never be true anymore. Can you extract the original message to an exported variable and use `errors.Is`?

2025-03-21 17:53 UTC, rkapka commented on changelog/kira_broadcast_slashings.md
> +- Removed redundant slashing verification checks in favor of using existing VerifyProposerSlashing function.
```suggestion
### Added 
- Added immediate broadcasting of proposer slashings when equivocating blocks are detected during block processing.
```

I would include only this in the changelog because that's the only thing that really matters. Adding too many entries to a changelog fragment bloats the changelog

2025-03-21 17:53 UTC, rkapka commented on beacon-chain/sync/validate_beacon_blocks_test.go
> +func TestDetectAndBroadcastEquivocation_NoEquivocation(t *testing.T) {
Can you merge all these tests into one, using `t.Run` for each test case? That way you can set up things like `p := p2ptest.NewTestP2P(t)` only once, at the start of the test, and reduce test times.

Pseudocode:
```
func TestDetectAndBroadcastEquivocation() {
    p := p2ptest.NewTestP2P(t)
    (...)
    t.Run("no equivocation", ...
    t.Run("equivocation detected", ...
}
```

2025-03-21 17:54 UTC, rkapka commented
@shyam-patel-kira I left a few comments

2025-04-01 01:15 UTC, shyam-patel-kira commented
> @shyam-patel-kira I left a few comments

Thanks for the review @rkapka, I've pushed the changes let me know if anything needs to be changed

2025-04-02 14:28 UTC, rkapka submitted a review, later dismissed

2025-04-02 15:19 UTC, rkapka commented
@shyam-patel-kira `TestValidateBeaconBlockPubSub_SeenProposerSlot` is failing

2025-04-22 23:56 UTC, shyam-patel-kira commented
> @shyam-patel-kira `TestValidateBeaconBlockPubSub_SeenProposerSlot` is failing

fixed it

2025-04-24 20:35 UTC, merged